services:
  - type: web
    name: fastapi-backend
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "cd backend && uvicorn main:app --host 0.0.0.0 --port 10000"

    envVars:
      - key: JWT_SECRET
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: AMADEUS_CLIENT_ID
        sync: false
      - key: AMADEUS_CLIENT_SECRET
        sync: false
      - key: COHERE_API_KEY
        sync: false
